apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-mobile-config-job
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-mobile-config
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: keycloak
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak-mobile-config
        app.kubernetes.io/component: configuration
    spec:
      restartPolicy: OnFailure
      serviceAccountName: default
      containers:
      - name: keycloak-config
        image: quay.io/keycloak/keycloak:26.3.1
        command: ["/bin/bash"]
        args: ["/config/configure-mobile.sh"]
        env:
        - name: KEYCLOAK_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: padmini-keycloak-admin
              key: KEYCLOAK_ADMIN_USERNAME
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: padmini-keycloak-admin
              key: KEYCLOAK_ADMIN_PASSWORD
        volumeMounts:
        - name: config-script
          mountPath: /config
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config-script
        configMap:
          name: keycloak-mobile-config-script
          defaultMode: 0755
