apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  # CRDs
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.1/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.1/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  # Keycloak Operator deployment
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.1/kubernetes/kubernetes.yml

# Optional: Add labels to all resources
commonLabels:
  app.kubernetes.io/name: keycloak-operator
  app.kubernetes.io/version: "26.3.1"
  app.kubernetes.io/part-of: keycloak-operator-gitops

# Optional: Add annotations
commonAnnotations:
  managed-by: argocd
  source: gitops 