apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-admin-config-job
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "10"  # Final step after manual verification
  labels:
    app.kubernetes.io/name: keycloak-admin-config
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: keycloak
    app.kubernetes.io/managed-by: argocd
spec:
  template:
    metadata:
      name: keycloak-admin-config
      labels:
        app.kubernetes.io/name: keycloak-admin-config
        app.kubernetes.io/component: configuration
    spec:
      # Use Keycloak image to have access to kcadm.sh
      containers:
      - name: keycloak-config
        image: quay.io/keycloak/keycloak:26.3.1
        command: ["/bin/bash"]
        args: ["/scripts/configure-keycloak.sh"]
        env:
        # Admin credentials from secret
        - name: KEYCLOAK_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: padmini-keycloak-admin
              key: KEYCLOAK_ADMIN_USERNAME
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: padmini-keycloak-admin
              key: KEYCLOAK_ADMIN_PASSWORD
        # SMTP configuration from secret
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: padmini-keycloak-smtp
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: padmini-keycloak-smtp
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: padmini-keycloak-smtp
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: padmini-keycloak-smtp
              key: SMTP_PASSWORD
        - name: SMTP_AUTH
          value: "true"
        - name: SMTP_SSL
          value: "false"
        - name: SMTP_STARTTLS
          value: "true"
        volumeMounts:
        - name: config-script
          mountPath: /scripts
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config-script
        configMap:
          name: keycloak-config-script
          defaultMode: 0755
      restartPolicy: OnFailure
      # Ensure job runs after Keycloak is ready
      initContainers:
      - name: wait-for-keycloak
        image: curlimages/curl:7.85.0
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Waiting for Keycloak service to be ready..."
          until curl -s http://padmini-keycloak:8080/health/ready >/dev/null 2>&1; do
            echo "Keycloak not ready, waiting..."
            sleep 10
          done
          echo "Keycloak is ready!"
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400  # Keep job for 24 hours for debugging
