apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak-python-config
  namespace: keycloak

resources:
  - keycloak-python-config-job.yaml

commonLabels:
  app.kubernetes.io/name: keycloak-python-config
  app.kubernetes.io/component: configuration
  app.kubernetes.io/part-of: keycloak
