apiVersion: v1
kind: Secret
metadata:
  name: keycloak-smtp-secret
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-smtp
    app.kubernetes.io/part-of: keycloak
    app.kubernetes.io/component: smtp-config
type: Opaque
stringData:
  # SMTP Server Configuration
  host: "smtp.gmail.com"                    # Replace with your SMTP server
  port: "587"                               # SMTP port (587 for TLS, 465 for SSL)
  auth: "true"                              # Enable SMTP authentication
  ssl: "false"                              # Use SSL (set to "true" for port 465)
  starttls: "true"                          # Use STARTTLS (set to "true" for port 587)
  
  # SMTP Authentication
  user: "your-email@gmail.com"              # Replace with your SMTP username
  password: "your-app-password"             # Replace with your SMTP password/app password
  
  # Example configurations for common providers:
  #
  # Gmail (recommended):
  # host: smtp.gmail.com
  # port: "587"
  # auth: "true"
  # ssl: "false" 
  # starttls: "true"
  # user: your-gmail@gmail.com
  # password: your-app-password  # Use App Password, not regular password
  #
  # Outlook/Hotmail:
  # host: smtp-mail.outlook.com
  # port: "587"
  # auth: "true"
  # ssl: "false"
  # starttls: "true"
  # user: your-email@outlook.com
  # password: your-password
  #
  # AWS SES:
  # host: email-smtp.us-east-1.amazonaws.com
  # port: "587"
  # auth: "true"
  # ssl: "false"
  # starttls: "true"
  # user: your-aws-ses-smtp-username
  # password: your-aws-ses-smtp-password
  #
  # SendGrid:
  # host: smtp.sendgrid.net
  # port: "587"
  # auth: "true"
  # ssl: "false"
  # starttls: "true"
  # user: apikey
  # password: your-sendgrid-api-key
