apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak-realms
  namespace: keycloak

resources:
  - padmini-realm-import.yaml
  # Note: keycloak-smtp-secret-template.yaml is a template file
  # Create the actual secret manually or via CI/CD with real credentials

commonLabels:
  app.kubernetes.io/part-of: keycloak
  app.kubernetes.io/component: realm-config
  app.kubernetes.io/managed-by: keycloak-operator
