apiVersion: k8s.keycloak.org/v1
kind: Keycloak
metadata:
  name: example-keycloak
  namespace: keycloak-system
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-service
    name: keycloak
    username: keycloak
    passwordSecret:
      name: keycloak-db-secret
      key: password
    port: 5432
  http:
    enabled: true
  https:
    enabled: false
  version: "26.3.1"
  image: quay.io/keycloak/keycloak:26.3.1
  imagePullPolicy: IfNotPresent
  keycloakDeploymentSpec:
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  service:
    type: ClusterIP
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080" 