apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: padmini-keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgresql.keycloak.svc.cluster.local
    name: keycloak
    username: keycloak  # Specify directly
    passwordSecret:
      name: keycloak-postgresql
      key: password
    port: 5432
  http:
    httpEnabled: true
    httpPort: 8180
    httpsPort: 8543
    tlsSecret: keycloak-tls-secret
  hostname:
    hostname: https://iam.padmini.systems
    admin: https://iam.padmini.systems/admin
    strict: false
    backchannelDynamic: true
  features:
    enabled:
      - docker
      - authorization
    disabled:
      - admin
      - step-up-authentication
  transaction:
    xaEnabled: false 
  proxy:
    headers: xforwarded
