apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: padmini-keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgresql.keycloak.svc.cluster.local
    name: keycloak
    username: keycloak  # Specify directly
    passwordSecret:
      name: keycloak-postgresql
      key: password
    port: 5432
  http:
    enabled: false
  https:
    enabled: true
    tlsSecret: keycloak-tls-secret
  hostname:
    hostname: iam.padmini.systems
  proxy:
    headers: xforwarded
