name: Deploy Keycloak Infrastructure via ArgoCD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubeconfig
        run: |
          echo "${{ secrets.PSYS_CENTOS_1_KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.2'

      - name: Verify Kustomize Configuration
        run: |
          kubectl kustomize keycloak-operator
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Apply Keycloak Operator ArgoCD Application
        run: |
          kubectl apply -f argocd-apps/keycloak-operator-app.yaml
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Apply PostgreSQL ArgoCD Application
        run: |
          kubectl apply -f argocd-apps/postgresql/postgresql-app.yaml
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Apply Certificates ArgoCD Application
        run: |
          kubectl apply -f argocd-apps/certificates/certificates-app.yaml
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Apply Keycloak Instance ArgoCD Application
        run: |
          kubectl apply -f argocd-apps/keycloak/keycloak-instance-app.yaml
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Verify Keycloak Operator Deployment
        run: |
          kubectl get pods -n keycloak
          kubectl get crd | grep keycloak
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Verify PostgreSQL Deployment
        run: |
          kubectl get pods -n keycloak-db
          kubectl get svc -n keycloak-db
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Verify Certificates Deployment
        run: |
          kubectl get certificates -n keycloak
          kubectl get secrets -n keycloak | grep tls
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Verify Keycloak Instance Deployment
        run: |
          kubectl get keycloaks -n keycloak
          kubectl get pods -n keycloak -l app=keycloak
        env:
          KUBECONFIG: ./kubeconfig.yaml
