name: Deploy Keycloak Operator via ArgoCD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubeconfig
        run: |
          echo "${{ secrets.PSYS_CENTOS_1_KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.2'

      - name: Verify Kustomize Configuration
        run: |
          kubectl kustomize k8s/keycloak-operator
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Apply ArgoCD Application
        run: |
          kubectl apply -f k8s/argocd-apps/keycloak-operator-app.yaml
        env:
          KUBECONFIG: ./kubeconfig.yaml

      - name: Verify Keycloak Operator Deployment
        run: |
          kubectl get pods -n keycloak
          kubectl get crd | grep keycloak
        env:
          KUBECONFIG: ./kubeconfig.yaml 